version: "3.8"

services:
  rmq-stream-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config/config.yaml:ro
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - rabbitmq

networks:
  rabbitmq:
    external: false
